### ISSUE TITLE
Allow to view team details without being logged in

### ISSUE THREAD

**Issue by NilsIrl** [ractf/core#1]
Currently if a user tries to view a team's details, they get redirected to the login page.

It would be nice if it was possible to view team details without having to be logged in.

**Comment by Bentechy66** [comment]
I believe this is a feature intended to increase conversions, but open to suggestions and comments

**Comment by david-cooke** [comment]
We have no plans to change this for the 2020 ctf. I think its a sane default for most ctfs, theres some public info to show you how big the ctf is but to actually view anything you have to sign up. I will probably make this configurable in the future as some ctfs will want it public, and some will want even the team list to be private.
