### ISSUE TITLE
Django Prometheus Crash

### ISSUE THREAD

**Issue by thebeanogamer** [ractf/core#164]
The Prometheus endpoint is crashing a lot.

https://sentry.io/organizations/ractf/issues/2563312965/
https://sentry.io/organizations/ractf/issues/2538518045/

Restarting the stack still seems to fix.

```py
{redis.command: GET, redis.key: :1:correct_solve_count}
```

**Comment by thebeanogamer** [comment]
This seems to be a result of sharing metrics between backend and websockets. The solution is probably a new endpoint within `/ws/` to just serve websockets metrics. Assigning to @jchristgit.

**Comment by jchristgit** [comment]
Fix is merged.
