### ISSUE TITLE
CTFTime Endpoint Still Has DRF UI

### ISSUE THREAD

**Issue by thebeanogamer** [ractf/core#165]

**Comment by david-cooke** [comment]
Thanks for reporting this bug! You can pen a pull request [here](https://github.com/ractf/core/compare)!

**Comment by jerbob** [comment]
Good evening **thebeanogamer**! :smile: 

It looks like you opened an issue without any relevant context... :disappointed: 

Next time, please use the provided "issue template" for bug reporting as a guide for what to include in your bug report. :memo:
