### ISSUE TITLE
Remove CIText dependency

### ISSUE THREAD

**Issue by david-cooke** [ractf/core#189]
**Is your feature request related to a problem? Please describe.**
Core currently depends on CIText for some name fields, this isn't necessary and we should remove it.

**Describe the solution you'd like**
Replace CIText with standard text fields and use case insensitive queries instead.

**Additional context**
This isn't as urgent as SQLite now support CIText, but we're still unnecessarily breaking other databases.

**Comment by ConnorMcF** [comment]
https://user-images.githubusercontent.com/3227315/149593374-4980ca9d-fdaf-4639-8dde-ff0c561f5784.mov
