### ISSUE TITLE
Admin-on-Admin impersonation termination unexpected behavior

### ISSUE THREAD

**Issue by AtomicNicos** [ractf/core#192]
**Describe the bug**
As admin, when impersonating another admin, the "Logout" button terminates your impersonation but also your own session.

**To Reproduce**
1. Have two admins and be one of them
2. Impersonate the other
3. Press logout
4. See login screen / error

**Expected behavior**
End Impersonation should restore own session.

**Comment by ConnorMcF** [comment]
https://user-images.githubusercontent.com/3227315/149593221-223692ea-bede-4a1c-99c2-5edae47e53b1.mov
