### ISSUE TITLE
Andromeda integration timeouts

### ISSUE THREAD

**Issue by 0xAda** [ractf/core#196]
**Describe the bug**
If polaris/andromeda is running slow, backend workers can be killed by gunicorn

**To Reproduce**
1. Set polaris on fire
2. Make a request proxied through backend
3. The worker will be killed

**Expected behavior**
Backend should timeout the request before gunicorn kill it and handle the error properly

**Comment by thebeanogamer** [comment]
Default timeout is 30 seconds ([source](https://docs.gunicorn.org/en/stable/settings.html#timeout)). Ideally we'd dynamically check that and adapt the Polaris timeout around that. Failing that, we just assume it's 30 seconds.

This should just be a cause of sticking some timeouts on the HTTP requests here ([details](https://2.python-requests.org/en/master/user/quickstart/#timeouts)) and catching the appropriate exception ([requests.Timeout](https://2.python-requests.org/en/master/api/#requests.Timeout)).

https://github.com/ractf/core/blob/7103a40577ccdf1a77b2297289f8d37949f666cd/src/andromeda/client.py#L10-L25

**Comment by thebeanogamer** [comment]
I can't find anywhere online that says how to read the Gunicorn worker timeout. Either we hard code it in gunicorn_config.py or we just assume that it's 30 seconds. To be honest, if Polaris hasn't replied within a couple of seconds it's probably not going to.

**Comment by jchristgit** [comment]
Hard coding is fine to me. That said, I don't think we should make the timeout here reliant on the timeout of the WSGI server, part of the niceties of WSGI is to be able to switch server easily. Isn't a timeout of 30 seconds already very very optimistic? Why would the request take 30 seconds?

**Comment by david-cooke** [comment]
Changing the timeouts for gunicorn wouldn't really be a fix IMO, when Polaris was on fire requests would block for upwards of 6 minutes, would be a fairly easy fix to just add a shorter timeout to the request from core.
