### ISSUE TITLE
FR: Option for points recalculation (triggered or automatic)

### ISSUE THREAD

**Issue by AtomicMaya** [ractf/core#200]
**Is your feature request related to a problem? Please describe.**
If a challenge has been found to be too complicated, but still has been solved by at least one team, it is possible for admins to change the value of a challenge (or if too easy, do the opposite).

 This however does not trigger a recount of the points gained by the people that have already submitted the challenge.

**Describe the solution you'd like**
Either an admin triggered event of "recount all the points with the current challenge / hint values" or an automatic event when a challenge / hint has it's points values edited, that all respondents/consumers thereof have their points recalculated.

**Comment by Bentechy66** [comment]
POST /api/v2/scorerecalculator/ with admin credentials

**Comment by AtomicNicos** [comment]
This is not documented on the client-side :)

**Comment by david-cooke** [comment]
I'll add this to the post_save handler for challenges at some point
