### ISSUE TITLE
Add Celery

### ISSUE THREAD

**Issue by 0xAda** [ractf/core#207]
We need to add celery

- clean up preevent cache generation
- email sending
- various events we might want to handle on event open/end
- discord webhooks

**Comment by thebeanogamer** [comment]
@jerbob I defer to you here, but presumably this means we're going to need to add another container? We need to consider how that works with self-hosted instances, perhaps a job for the RACTF public address system? Would probably involve us having to write a migration tool for Docker Compose files into ractl...

I don't really want to do the hacky solution of running this as a background process in the `backend` container.

**Comment by jerbob** [comment]
Ye s to cobfirm we need another container

**Comment by jerbob** [comment]
no no nonono wait wait wait wait wait

**Comment by thebeanogamer** [comment]
If we're going to change this, it should probably be its own issue

**Comment by 0xAda** [comment]
Closing in favour of doing literally anything else
