### ISSUE TITLE
Dynamic Scoring

### ISSUE THREAD

**Issue by thebeanogamer** [ractf/core#232]
We need to support decreasing the number of points for a challenge as more people score it.

We supposedly already support this, but we should test that and fix it when it inevitably doesn't.

**Comment by thebeanogamer** [comment]
Currently, this will absolutely hammer core because it will trigger all shell clients to re-request the challenge every time it is solved.

@NicholasG04's solution is to add a new websocket message which already contains the updated score. This will still hurt core, but not nearly as hard as every client requesting all details every time there's a solve.

**Comment by NicholasG04** [comment]
i take no responsibility, it is beano's fault if it all goes wrong.
https://github.com/ractf/shell/issues/57
