### ISSUE TITLE
Maximum Username Length

### ISSUE THREAD

**Issue by thebeanogamer** [ractf/core#235]
Whilst we don't technically _need_ to limit the username length, if we don't people will abuse it.

**Comment by david-cooke** [comment]
We already limit it to 36 characters. Is this too long? How long of a name
can frontend display?

**Comment by joe-butler2** [comment]
It was an accident

**Comment by jchristgit** [comment]
@joe-butler2 thanks for your contribution.

@thebeanogamer as Ada mentioned, we already have a length limit of 36 in-place.

**Comment by david-cooke** [comment]
the limit doesnt work lmao

**Comment by jchristgit** [comment]
@david-cooke what does that mean?

**Comment by david-cooke** [comment]
Django doesn't validate it at runtime and postgres doesn't enforce the limit
