### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by jerbob** [ractf/core#27]

**Comment by priya-pri** [comment]
Hi ,can you assign me this ?I would like to contribute to this

**Comment by OmkarGeedh** [comment]
I would like to contribute to this

**Comment by ragreenburg** [comment]
What exactly are you looking for here? A detailed description on what RACTF is or something else?

**Comment by NicholasG04** [comment]
Jeremiah, this is the worst issue I've ever seen. Absolutely disgusted.

**Comment by david-cooke** [comment]
Hi ,can you assign me this ?I would like to contribute to this

**Comment by thebeanogamer** [comment]
Hi ,can you assign me this ?I would like to contribute to this
