### ISSUE TITLE
Pre-event check only checks beginning of flag

### ISSUE THREAD

**Issue by AtomicNicos** [ractf/core#278]
**Describe the bug**
The Pre-event check will only check that the beginning of the CTF flag is correct, but not the end (closing curly bracket).

ie. if `flag` is the flag format it'll detect:
- `notflag{foo}`
- `bar`

but not: 
- `flag{baz`

**To Reproduce**
1. Set a flag format
2. Create a challenge with flag `<format>{baz`
3. Fill the rest of the fields with filler
4. See lack of error in Pre-event check

**Expected behavior**
It should show up in the Pre-event check as a malformed flag.

**Screenshots**
A random challenge with a malformed flag:
![image](https://user-images.githubusercontent.com/18284503/172468243-123803dd-e91e-4ffa-a2cb-a42264ae703a.png)

The pre-event check without the malformed challenge:
![image](https://user-images.githubusercontent.com/18284503/172468376-de581a35-f75f-4a3d-8a6a-61fceed7129d.png)

**Comment by 0x4da** [comment]
Off the top of my head I'm not entirely sure how flag formats work, do we support flag formats that don't use curly braces?
