### ISSUE TITLE
picoCTF Shell Integration

### ISSUE THREAD

**Issue by chop0** [ractf/core#67]
**Is your feature request related to a problem? Please describe.**
Problem hosting is an important feature for running CTFs, and picoCTF Shell, in my opinion, is one of the most flexible platforms for doing so. It supports Docker problems and gives each user an ssh environment for problem-solving, regardless of whether or not they have a Linux distro installed.
**Describe the solution you'd like**
picoCTF Shell integration built into the platform, such that challenges deploy through picoCTF and onto the picoCTF shell can be loaded into raCTF.
**Describe alternatives you've considered**
Andromeda is the officially sanctioned platform for challenge hosting, however, it lacks many of the features, documentation, and stability of the picoCTF shell. Having integration between these platforms would greatly improve the ease of hosting challenges, and improve the user experience significantly.

**Comment by jerbob** [comment]
On second thoughts, this should be solved about the same time we hit our 100% uptime SLA. Reopening.

**Comment by jerbob** [comment]
![](https://cdn.discordapp.com/emojis/750350748746907669.gif?v=1)

**Comment by Bentechy66** [comment]
![](https://cdn.discordapp.com/emojis/750350748746907669.gif?v=1)

**Comment by thebeanogamer** [comment]
![](https://cdn.discordapp.com/emojis/750350748746907669.gif?v=1)

**Comment by david-cooke** [comment]
![image](https://user-images.githubusercontent.com/8531139/104095799-c2afc700-5290-11eb-840c-7e3061a705f1.png)

**Comment by david-cooke** [comment]
how the fuck did that not animate

**Comment by david-cooke** [comment]
![image](https://user-images.githubusercontent.com/8531139/104095819-d9561e00-5290-11eb-813b-5846e800ee2a.png)

**Comment by david-cooke** [comment]
hm

**Comment by david-cooke** [comment]
![](https://cdn.discordapp.com/emojis/750350748746907669.gif?v=1)

**Comment by thebeanogamer** [comment]
Thanks Dave
