### ISSUE TITLE
Deprecation of SMD API format

### ISSUE THREAD

**Issue by david-cooke** [ractf/core#92]
The backend currently uses a `{"s": bool, "m": str, "d": any}` response format, the s is redundant because http status codes tell you that and the format itself is responsible for causing a lot of mess in the code, it started out as a renderer but now with things like `FormattedResponse` its getting a bit much. I'm not too sure on what the path would be to removed this, but we already implement `X-Reasonable`, we could probably start making sure that format works better and add a `X-Deprecated-Response-Format` header or something to the api responses using smd.

**Comment by ConnorMcF** [comment]
https://user-images.githubusercontent.com/3227315/113523031-45e56e00-959d-11eb-9822-48fc27f3b66a.mp4
