### ISSUE TITLE
Internal server error on signup (Sendgrid)

### ISSUE THREAD

**Issue by clubby789** [ractf/core#97]
**Describe the bug**
Registering a user displays an error message, but still registers the user. The traceback shows a 400 error being returned by the Sendgrid API

**To Reproduce**
1. Use the installer
2. Configure mail with sendgrid and the SG API key
3. Register a user

**Expected behavior**
A verification email to be sent.

**Screenshots**
![Error](https://media.discordapp.net/attachments/831886312529068044/831886506552459304/unknown.png?width=832&height=312)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Are you using the docker image? Yes
 - Database: postgres, as setup by the installer.

**Comment by clubby789** [comment]
Figured it  out. Sending the mail requires the environment vars `EMAIL_ADDRESS` and `EMAIL_NAME` to be set, otherwise `nulls` are sent to the API, resulting in a 400. These keys were not added to the docker-compose file by the installer.

**Comment by david-cooke** [comment]
@Bentechy66

**Comment by david-cooke** [comment]
closing because resolved
